#!/usr/bin/env python3
"""BRG kit builder — generates the shortcode docs from kit/registry.json (the source
of truth), and stamps each component with a version + contract hash. Pattern borrowed
from fc-brands (temper/kit). Edit the registry, then run this — never edit the docs by hand.

  python3 kit/build.py            regenerate SHORTCODES.md + docs/shortcode-index.html
  python3 kit/build.py --restamp  bump version + re-hash any component whose contract moved
  python3 kit/build.py --check    exit 1 if a contract moved un-bumped, or the docs are stale
"""
import json, hashlib, sys, os, html, datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _guard import refuse_if_worktree

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REG  = os.path.join(ROOT, 'kit', 'registry.json')
IDX  = os.path.join(ROOT, 'docs', 'shortcode-index.html')
MD   = os.path.join(ROOT, 'SHORTCODES.md')
E    = html.escape

def contract(c):
    """Hash of shortcode + type + every attr name=default. Prose is excluded on purpose."""
    canon = c['shortcode'] + '|' + c['type'] + '|' + '|'.join(
        f"{a['name']}={a.get('default','')}" for a in c.get('attrs', []))
    return hashlib.sha256(canon.encode('utf-8')).hexdigest()[:12]

GROUPS = [('pages', 'Whole-page shortcodes'), ('sections', 'Section shortcodes (stack these to build a page)'),
          ('chrome', 'Chrome (nav + footer)'), ('utility', 'Utility')]

# ---- SHORTCODES.md (markdown) -------------------------------------------------
def render_md(reg):
    L = ['# BRG — Shortcode Reference', '',
         '> GENERATED from `kit/registry.json` by `kit/build.py`. Edit the registry, then rerun. '
         'Do not edit this file by hand.', '',
         'Pages/sections are code fragments on Netlify pulled natively into WordPress; edit a fragment '
         '→ `git push` → live in ~60s. The nav is a WordPress menu (Appearance → Menus).', '',
         '## Shortcodes', '', '| Shortcode | Type | Attributes |', '|---|---|---|']
    for c in reg['components']:
        attrs = ', '.join(f"`{a['name']}`" for a in c.get('attrs', [])) or '—'
        L.append(f"| `[{c['shortcode']}]` | {c['type']} | {attrs} |")
    L += ['', '## Attributes by shortcode', '']
    for c in reg['components']:
        L.append(f"### `[{c['shortcode']}]` — {c['summary']}  ·  v{c['version']} `{c['contract']}`")
        if c.get('aliases'):
            L.append(f"Aliases: {c['aliases']}")
        L += ['', '| Attr | Default | Does |', '|---|---|---|']
        for a in c.get('attrs', []):
            opt = f" ({' / '.join(a['options'])})" if a.get('options') else ''
            L.append(f"| `{a['name']}`{opt} | `{a.get('default') or '—'}` | {a.get('doc','')} |")
        L.append('')
    L += ['## Global', '']
    for g in reg.get('globals', []):
        L.append(f"- `{g['name']}` (default `{g['default']}`) — {g['doc']}")
    L += ['', f"_registry v{reg['version']} · built {stamp()}_", '']
    return '\n'.join(L)

# ---- docs/shortcode-index.html (visual) --------------------------------------
CSS = """  :root{ --yellow:#FCE200; --teal:#19C7C2; --bg:#0f0e0d; --bg2:#17150f; --card:#1c1a16;
    --line:rgba(255,255,255,.10); --ink:#f4f1ea; --dim:rgba(244,241,234,.6);
    --mono:"SFMono-Regular",Menlo,Consolas,monospace; --sans:"Montserrat",system-ui,sans-serif; }
  *{box-sizing:border-box;} html,body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);-webkit-font-smoothing:antialiased;}
  header.top{position:sticky;top:0;z-index:5;background:rgba(15,14,13,.92);backdrop-filter:blur(8px);
    border-top:5px solid var(--yellow);border-bottom:1px solid var(--line);padding:20px clamp(20px,4vw,56px);
    display:flex;align-items:center;gap:18px;flex-wrap:wrap;}
  .brand b{background:var(--yellow);color:#231F20;font-weight:800;padding:.1em .4em;}
  .brand span{font-size:.7rem;letter-spacing:.22em;text-transform:uppercase;color:var(--dim);margin-left:8px;}
  h1{font-size:1.05rem;margin:0;font-weight:800;letter-spacing:.02em;text-transform:uppercase;}
  .ver{margin-left:auto;font-family:var(--mono);font-size:.72rem;color:var(--dim);border:1px solid var(--line);border-radius:999px;padding:5px 12px;}
  .filters{display:flex;gap:8px;flex-wrap:wrap;padding:16px clamp(20px,4vw,56px) 0;}
  .chip{font:600 .72rem/1 var(--sans);letter-spacing:.1em;text-transform:uppercase;color:var(--dim);
    background:var(--card);border:1px solid var(--line);border-radius:999px;padding:9px 15px;cursor:pointer;}
  .chip.on{background:var(--yellow);color:#231F20;border-color:var(--yellow);}
  main{padding:20px clamp(20px,4vw,56px) 64px;}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,420px),1fr));gap:18px;align-items:start;}
  .card{background:var(--card);border:1px solid var(--line);border-radius:12px;overflow:hidden;}
  .card h2{margin:0;font-family:var(--mono);font-size:.95rem;font-weight:600;color:var(--yellow);
    padding:16px 18px;background:var(--bg2);border-bottom:1px solid var(--line);word-break:break-word;}
  .card .meta{float:right;font-size:.6rem;letter-spacing:.06em;color:var(--dim);font-family:var(--mono);}
  table{width:100%;border-collapse:collapse;} th,td{text-align:left;vertical-align:top;padding:11px 18px;font-size:.86rem;
    line-height:1.5;border-bottom:1px solid var(--line);white-space:normal;word-break:break-word;}
  th{font-size:.6rem;letter-spacing:.14em;text-transform:uppercase;color:var(--dim);font-weight:700;white-space:nowrap;}
  th:first-child,td:first-child,th:nth-child(2),td:nth-child(2){width:1%;}
  tr:last-child td{border-bottom:0;} td.a{font-family:var(--mono);color:var(--teal);white-space:nowrap;}
  td.d{font-family:var(--mono);color:var(--dim);} .note{padding:12px 18px;font-size:.82rem;color:var(--dim);line-height:1.5;border-top:1px solid var(--line);background:rgba(0,0,0,.15);}
  code{font-family:var(--mono);background:rgba(255,255,255,.07);border-radius:4px;padding:.08em .4em;font-size:.86em;}
  .sec-title{grid-column:1/-1;font-size:.7rem;letter-spacing:.2em;text-transform:uppercase;color:var(--dim);margin:14px 2px 0;border-top:1px solid var(--line);padding-top:22px;}
  .sec-title:first-child{border-top:0;padding-top:0;} footer{padding:0 clamp(20px,4vw,56px) 60px;color:var(--dim);font-size:.85rem;}"""

def card(c):
    rows = ''.join(
        f'<tr><td class="a">{E(a["name"])}</td><td class="d">{E(a.get("default") or "—")}</td>'
        f'<td>{E(a.get("doc",""))}</td></tr>' for a in c.get('attrs', [])) \
        or '<tr><td colspan="3">No attributes.</td></tr>'
    note = f'<div class="note">Aliases: {E(c["aliases"])}</div>' if c.get('aliases') else ''
    return (f'<div class="card" data-g="{c["group"]}"><h2>[{E(c["shortcode"])}]'
            f'<span class="meta">{c["type"]} · v{c["version"]} {c["contract"]}</span></h2>'
            f'<table><tr><th>Attr</th><th>Default</th><th>Does</th></tr>{rows}</table>{note}</div>')

def render_html(reg):
    chips = '<button class="chip on" data-f="all">All</button>' + ''.join(
        f'<button class="chip" data-f="{g}">{g.title()}</button>' for g, _ in GROUPS)
    body = ''
    for g, title in GROUPS:
        cs = [c for c in reg['components'] if c['group'] == g]
        if not cs: continue
        body += f'<div class="sec-title" data-g="{g}">{title}</div>' + ''.join(card(c) for c in cs)
    glob = ''.join(f'<tr><td class="a">{E(x["name"])}</td><td class="d">{E(x["default"])}</td><td>{E(x["doc"])}</td></tr>' for x in reg.get('globals', []))
    body += ('<div class="sec-title" data-g="all">Global</div>'
             f'<div class="card" data-g="all"><h2>global</h2><table><tr><th>What</th><th>Default</th><th>Does</th></tr>{glob}</table></div>')
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>BRG — Shortcode Index</title>
<!-- GENERATED by kit/build.py from kit/registry.json — do not edit by hand. -->
<style>{CSS}</style></head><body>
<header class="top"><span class="brand"><b>BRG</b><span>Blacktop Restaurant Group</span></span>
<h1>Shortcode Index</h1><span class="ver">registry v{reg['version']} · {stamp()}</span></header>
<div class="filters" id="filters">{chips}</div>
<main><div class="grid">{body}</div></main>
<footer>Generated from <code>kit/registry.json</code>. Edit the registry, run <code>python3 kit/build.py</code>.</footer>
<script>var chips=document.querySelectorAll('.chip'),items=document.querySelectorAll('[data-g]');
document.getElementById('filters').addEventListener('click',function(e){{var b=e.target.closest('.chip');if(!b)return;
chips.forEach(function(c){{c.classList.toggle('on',c===b);}});var f=b.dataset.f;
items.forEach(function(el){{el.style.display=(f==='all'||el.dataset.g===f)?'':'none';}});}});</script>
</body></html>"""

def stamp():
    return "registry-generated"   # no wall-clock: keep output deterministic for --check

def main():
    refuse_if_worktree('kit/build.py')
    mode = sys.argv[1] if len(sys.argv) > 1 else ''
    reg = json.load(open(REG))
    comps = reg['components']

    drift = []
    for c in comps:
        cc = contract(c)
        stored = c.get('contract')
        if stored is None:                       # first stamp
            c['version'], c['contract'] = 1, cc
        elif stored != cc:
            drift.append((c['id'], stored, cc))

    if mode == '--restamp':
        for c in comps:
            cc = contract(c)
            if c.get('contract') != cc:
                c['version'] = c.get('version', 1) + 1
                c['contract'] = cc
        json.dump(reg, open(REG, 'w'), indent=2, ensure_ascii=False); open(REG,'a').write('\n')
        print("restamped."); return _print_ledger(comps)

    html_out, md_out = render_html(reg), render_md(reg)

    if mode == '--check':
        stale = drift or (open(IDX).read() != html_out) or (open(MD).read() != md_out)
        if drift:
            for i, s, cc in drift:
                print(f"DRIFT: {i} contract moved {s} -> {cc} without a version bump. Run: python3 kit/build.py --restamp")
        if open(IDX).read() != html_out or open(MD).read() != md_out:
            print("STALE: docs differ from the registry. Run: python3 kit/build.py")
        print("check FAILED" if stale else "check OK")
        sys.exit(1 if stale else 0)

    # normal build: stamp any first-time components, write docs
    if any(c.get('contract') == contract(c) and 'contract' in c for c in comps):
        json.dump(reg, open(REG, 'w'), indent=2, ensure_ascii=False); open(REG,'a').write('\n')
    open(IDX, 'w').write(html_out); open(MD, 'w').write(md_out)
    if drift:
        for i, s, cc in drift:
            print(f"WARNING: {i} contract moved {s} -> {cc}. Run --restamp to bump the version.")
    print(f"generated {os.path.relpath(MD, ROOT)} + {os.path.relpath(IDX, ROOT)}")
    _print_ledger(comps)

def _print_ledger(comps):
    print("\nid                 ver  contract")
    for c in comps:
        print(f"{c['id']:18} v{c.get('version')}  {c.get('contract')}")

if __name__ == '__main__':
    main()
