#!/usr/bin/env python3
"""Build the lab in two flavours from one template.

  artifact : fully self-contained (Blanco inlined, CARDS inline) — the URL Sean opens
  kit      : Blanco linked, CARDS lifted into lab-cards.js — the copy conti pushes

CARDS lives in ONE file for the kit build so lab.html and lab-full.html cannot
disagree about which variants exist. Generating one copy from the other would have
left two copies plus a mechanism; deleting the copy leaves neither.
"""
import base64, json, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[2]
TPL  = HERE / "lab-template.html"
LINES= HERE / "lines-centrelines.json"
WOFF = REPO / "website/assets/media/fonts/BlancoCavelary.woff2"
FONT = "https://blacktoprg.netlify.app/assets/media/fonts/BlancoCavelary.woff2"

# Salient's own squiggle-underline-2 path, lifted from the served Baked Bear markup as a
# comparison swatch. src_sha is "salient-ref" so it can never be mistaken for something
# derived from Sean's artwork by derive-centrelines.py.
BB_SQUIGGLE = {"vb": "-320 -70.8161 640.4 59.82",
  "d": "M-300,-56 C-50,-72 298,-65 300,-59 C332,-53 -239,-36 -255,-27 C-271,-18 -88,-24 91,-20",
  "sw": 7.8, "src_sha": "salient-ref"}
BB_SQUIGGLE["centre"] = BB_SQUIGGLE["d"]

def split_cards(h):
    a, b = "/*__CARDS_START__*/\n", "/*__CARDS_END__*/\n"
    i, j = h.index(a), h.index(b)
    return h[:i], h[i+len(a):j], h[j+len(b):]

def build():
    for f in (TPL, LINES, WOFF):
        if not f.exists():
            raise SystemExit(f"REFUSING TO BUILD: missing {f}")
    h = TPL.read_text()
    L = json.loads(LINES.read_text())
    L["_bb_squiggle"] = BB_SQUIGGLE
    head, cards, tail = split_cards(h)

    # ---- artifact: everything inline
    art = (head + cards + tail)
    # Blanco is base64'd from the repo's own woff2 at build time — no stored copy to go stale.
    art = art.replace("__BLANCO__", base64.b64encode(WOFF.read_bytes()).decode())
    art = art.replace("__LINES__", json.dumps(L))
    assert "__" not in art.replace("__MACOSX",""), "unfilled token in artifact build"
    ART = pathlib.Path(sys.argv[1]) if len(sys.argv)>1 else HERE/"underline-lab.html"
    ART.write_text(art)

    # ---- kit: font linked, CARDS lifted out
    stamp = "".join(sorted(v["src_sha"] for k,v in L.items() if not k.startswith("_")))
    kit = head + tail
    kit = kit.replace(
        "@font-face{font-family:'Blanco Cavelary';src:url(data:font/woff2;base64,__BLANCO__) format('woff2');font-weight:400;font-display:block}",
        f"@font-face{{font-family:'Blanco Cavelary';src:url('{FONT}') format('woff2');font-weight:400;font-display:block}}")
    kit = kit.replace("__LINES__", json.dumps(L))
    # CARDS must be defined before the script that consumes it
    kit = kit.replace("<script>", '<script src="lab-cards.js"></script>\n<script>', 1)
    kit = (f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- BRG kit — Lab. DELIBERATELY NOT GENERATED by kit/build-kit.py; authored by expo,
     pushed by conti. Built from notes/explorer/studies/build-lab.py.
     centreline-provenance: {stamp}
     CARDS lives in lab-cards.js, loaded by BOTH this page and lab-full.html, so the two
     cannot disagree about which variants exist. Do not inline it back. -->
""" + kit)
    assert "__" not in kit.replace("__MACOSX",""), "unfilled token in kit build"
    assert "const CARDS=[" not in kit, "CARDS still inline in the kit build"
    (REPO/"notes/explorer/studies/lab.html").write_text(kit)

    js = ("// BRG kit — the ONE card list. Loaded by lab.html AND lab-full.html.\n"
          "// Generated by notes/explorer/studies/build-lab.py — edit the template, not this.\n"
          "// Cards with nofull:true have no full-page view on purpose; see their `why`.\n"
          + cards)
    (REPO/"notes/explorer/studies/lab-cards.js").write_text(js)

    ids = re.findall(r"id:'([A-Za-z0-9-]+)'", cards)
    assert len(ids) == len(set(ids)), "duplicate card id"
    print(f"artifact {len(art)//1024}KB · kit {len(kit)//1024}KB · lab-cards.js {len(js)//1024}KB")
    print(f"cards {len(ids)}: {' '.join(ids)}")
    nofull = [m for m in re.findall(r"id:'([A-Za-z0-9-]+)'[^{}]*?nofull:true", cards)]
    print(f"no full-page view: {nofull or 'none'}")

if __name__ == "__main__":
    build()
