#!/usr/bin/env python3
"""Build the lab in two flavours from one template.

  artifact : fully self-contained (Blanco inlined, CARDS inline) — the URL Sean opens
  kit      : Blanco linked, CARDS lifted into lab-cards.js — the copy conti pushes

CARDS lives in ONE file for the kit build so lab.html and lab-full.html cannot
disagree about which variants exist. Generating one copy from the other would have
left two copies plus a mechanism; deleting the copy leaves neither.
"""
import base64, json, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[2]
TPL  = HERE / "lab-template.html"
LINES= HERE / "lines-centrelines.json"
WOFF = REPO / "website/assets/media/fonts/BlancoCavelary.woff2"
FONT = "https://blacktoprg.netlify.app/assets/media/fonts/BlancoCavelary.woff2"

# Salient's own squiggle-underline-2 path, lifted from the served Baked Bear markup as a
# comparison swatch. src_sha is "salient-ref" so it can never be mistaken for something
# derived from Sean's artwork by derive-centrelines.py.
BB_SQUIGGLE = {"vb": "-320 -70.8161 640.4 59.82",
  "d": "M-300,-56 C-50,-72 298,-65 300,-59 C332,-53 -239,-36 -255,-27 C-271,-18 -88,-24 91,-20",
  "sw": 7.8, "src_sha": "salient-ref"}
BB_SQUIGGLE["centre"] = BB_SQUIGGLE["d"]

def _block(h, name):
    """The contents of a sentinel-marked block."""
    a, b = f"/*__{name}_START__*/\n", f"/*__{name}_END__*/"
    return h[h.index(a)+len(a):h.index(b)]

def _drop(h, name):
    """The template with that block removed entirely."""
    a, b = f"/*__{name}_START__*/\n", f"/*__{name}_END__*/"
    return h[:h.index(a)] + h[h.index(b)+len(b):]

def _unmark(h):
    """The template with sentinels stripped but every block left in place."""
    return re.sub(r"/\*__[A-Z]+_(?:START|END)__\*/\n?", "", h)

def build():
    for f in (TPL, LINES, WOFF):
        if not f.exists():
            raise SystemExit(f"REFUSING TO BUILD: missing {f}")
    h = TPL.read_text()
    L = json.loads(LINES.read_text())
    L["_bb_squiggle"] = BB_SQUIGGLE
    lines_blk = _block(h, "LINES")
    cards     = _block(h, "CARDS")

    # ---- artifact: everything inline, in original order
    art = _unmark(h)
    # Blanco is base64'd from the repo's own woff2 at build time — no stored copy to go stale.
    art = art.replace("__BLANCO__", base64.b64encode(WOFF.read_bytes()).decode())
    art = art.replace("__LINES__", json.dumps(L))
    assert "__" not in art.replace("__MACOSX",""), "unfilled token in artifact build"
    ART = pathlib.Path(sys.argv[1]) if len(sys.argv)>1 else HERE/"underline-lab.html"
    ART.write_text(art)

    # ---- kit: font linked, CARDS lifted out
    stamp = "".join(sorted(v["src_sha"] for k,v in L.items() if not k.startswith("_")))
    kit = _unmark(_drop(_drop(h, "LINES"), "CARDS"))
    kit = kit.replace(
        "@font-face{font-family:'Blanco Cavelary';src:url(data:font/woff2;base64,__BLANCO__) format('woff2');font-weight:400;font-display:block}",
        f"@font-face{{font-family:'Blanco Cavelary';src:url('{FONT}') format('woff2');font-weight:400;font-display:block}}")
    kit = kit.replace("__LINES__", json.dumps(L))
    # CARDS must be defined before the script that consumes it
    # both shared files must load BEFORE the script that consumes them
    # lab-sync.js FIRST: it may pull remote state and reload, so the earlier it runs the
    # less work gets thrown away. It is conti's file, self-contained, and degrades to
    # local-only if absent — but it degrades SILENTLY, hence the gate entry below.
    kit = kit.replace("<script>",
        '<script src="lab-sync.js"></script>\n'
        '<script src="lab-lines.js"></script>\n<script src="lab-cards.js"></script>\n<script>', 1)
    kit = (f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- BRG kit — Lab. DELIBERATELY NOT GENERATED by kit/build-kit.py; authored by expo,
     pushed by conti. Built from notes/explorer/studies/build-lab.py.
     centreline-provenance: {stamp}
     CARDS lives in lab-cards.js, loaded by BOTH this page and lab-full.html, so the two
     cannot disagree about which variants exist. Do not inline it back.

     DO NOT EDIT THIS FILE. It is overwritten wholesale by build-lab.py on the next
     promotion — a "Full page" link added here on 2026-08-17 was silently destroyed exactly
     that way. Changes go into notes/explorer/studies/lab-template.html, which is the source.
     The handoff is one-directional: expo -> conti -> website/kit/. -->
""" + kit)
    assert "__" not in kit.replace("__MACOSX",""), "unfilled token in kit build"
    assert "const CARDS=[" not in kit, "CARDS still inline in the kit build"
    # SHIP rides inside the CARDS block, so it lands in lab-cards.js — not lab.html.
    # Gating it against `kit` failed a correct build twice; check the blob that has it.
    assert "const SHIP=[" in js, "the shipping-form variants are missing from lab-cards.js"
    # Features Sean asked for, each of which has already been lost once by a rebuild
    # silently reverting an edit made to the DEPLOYED file. Losing one must fail the build,
    # not the review — he has been the regression test three times and cannot tell from
    # looking that the page has reverted.
    for needle, what in (
        ('href="lab-full.html?v=', 'the Full page link'),
        ('class="maybe"',          'the Adjust verdict button'),
        ("VERDICTS={yes:",         'the three-state verdict handler'),
        ('id="copyall"',           'the Copy all button'),
        ('ADJUST',                 'the Adjust block in the summary'),
        ('c.nofull?',              'the nofull opt-out'),
        ('function noteBox',       'the group / overall note boxes'),
        ("free('OVERALL'",         'the Overall block in the summary'),
        ('src="lab-sync.js"',      'the cross-device sync tag'),
        ('function parseMark',     'the asterisk delimiter parser'),
        ('function markPlan',      'the mark DECISION (parser alone is not enough)'),
        ("mode:'all'",             'the no-delimiter fallback — an empty mark kills every heading'),
        ('style:false',            'measure-only: a fallback must not STYLE the words'),
        ('--strokec',              'stroke colour routed off the text'),
        ('function attachBox',     'the single place that knows a .u needs a stroke box'),
        ('function renderShip',    'the attribute-driven renderer — section E'),

        ("mark.classList.contains('blk')", 'the blk branch — a bar is a sibling, not a wrapper'),

        ('function sectionPanel',  'the per-section variable panel'),
    ):
        assert needle in kit, f"MISSING FEATURE: {what} ({needle!r}) is not in the kit build"
    n = kit.count('<button class="yes">')
    assert kit.count('class="maybe"') == n == kit.count('<button class="no">'), \
        "verdict buttons are not three-per-card"
    assert "const L = {" not in kit and "const sv =" not in kit, "artwork still inline in the kit build"
    (REPO/"notes/explorer/studies/lab.html").write_text(kit)

    js = ("// BRG kit — the ONE card list. Loaded by lab.html AND lab-full.html.\n"
          "// Generated by notes/explorer/studies/build-lab.py — edit the template, not this.\n"
          "// Cards with nofull:true have no full-page view on purpose; see their `why`.\n"
          + cards)
    (REPO/"notes/explorer/studies/lab-cards.js").write_text(js)

    lines_js = ("// BRG kit — the ONE artwork source. Loaded by lab.html AND lab-full.html.\n"
        "// Generated by build-lab.py. L carries every stroke WITH its derived `centre`;\n"
        "// sv(k,draw) strokes that centreline when draw is true. A copy of this without\n"
        "// `centre` makes every draw variant trace the artwork OUTLINE instead — a lasso,\n"
        "// not a pen. That is exactly what a stale second copy did on 2026-08-17.\n"
        + lines_blk.replace("__LINES__", json.dumps(L)).strip() + "\n")
    for nm, blob in (("lab-cards.js", js), ("lab-lines.js", lines_js)):
        assert "__" not in blob.replace("__MACOSX", ""), f"unfilled token in {nm}"
    assert '"centre"' in lines_js, "lab-lines.js has no centrelines — draw variants would trace outlines"
    assert '"cvb"' in lines_js and "l.cvb" in lines_js, \
        "lab-lines.js lacks the centreline viewBox — every draw variant would start and end short"
    (REPO/"notes/explorer/studies/lab-lines.js").write_text(lines_js)

    # Syntax-check everything we emit. The build gated CONTENT and never gated SYNTAX, so an
    # unescaped apostrophe in a card's `why` reached pre-push instead of failing here.
    import subprocess, tempfile
    for name, blob in (("lab-cards.js", js), ("lab-lines.js", lines_js),
                       ("lab.html<script>", re.search(r"<script>(.*)</script>", kit, re.S).group(1)),
                       ("artifact<script>", re.search(r"<script>(.*)</script>", art, re.S).group(1))):
        with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as f:
            f.write(blob); tmp = f.name
        r = subprocess.run(["node", "--check", tmp], capture_output=True, text=True)
        if r.returncode:
            raise SystemExit(f"SYNTAX ERROR in {name}:\n{r.stderr.strip()[:600]}")

    ids = re.findall(r"id:'([A-Za-z0-9-]+)'", cards)
    assert len(ids) == len(set(ids)), "duplicate card id"
    print(f"artifact {len(art)//1024}KB · kit {len(kit)//1024}KB · "
          f"lab-cards.js {len(js)//1024}KB · lab-lines.js {len(lines_js)//1024}KB")
    print(f"cards {len(ids)}: {' '.join(ids)}")
    nofull = [m for m in re.findall(r"id:'([A-Za-z0-9-]+)'[^{}]*?nofull:true", cards)]
    print(f"no full-page view: {nofull or 'none'}")

if __name__ == "__main__":
    build()
