// BRG kit — the ONE card list. Loaded by lab.html AND lab-full.html.
// Generated by notes/explorer/studies/build-lab.py — edit the template, not this.
// Cards with nofull:true have no full-page view on purpose; see their `why`.
const CARDS=[
 {g:'gA',id:'A1',rev:4,changed:'Entrance rebuilt. It fired instantly because it sits on screen at load; every card now waits the same beat, so this enters exactly like A5.',t:'Wipe — your artwork, untouched',
  why:'Your line-careers-lg.svg exactly as exported, revealed with a clip-path. No re-export, nothing to redraw. The leading edge is a flat vertical cut.',
  html:'<p class="head blanco">Come work somewhere<br><span class="u wipe" data-k="line-careers-lg">you actually want to be</span></p>'},
 {g:'gA',id:'A2',rev:3,changed:'Rebuilt on a derived CENTRELINE. It was stroking the artwork outline, which traces the perimeter — a lasso, not a pen. Landed in v3; if it still looks like a trace, you are on a cached page.',t:'Draw — stroked centreline',
  why:'NOW 1.8s to match the reference — you said it was way too fast, and it was running on the global slider while the Salient cards held 1.8s. REBUILT earlier to stroke the derived centreline: it was stroking the artwork OUTLINE, which traces the shape\'s perimeter — a lasso, not a pen. It now strokes a CENTRELINE derived from your outline: I flattened the curves, took the midpoint between the top and bottom edge at 90 samples, and fitted a smooth path. Measured weight is 15.0 on every hero file and 5.0 on every nav file — dead uniform, which is what makes the centreline recoverable. No re-export needed.',
  html:'<p class="head blanco">Come work somewhere<br><span class="u draw slow" data-k="line-careers-lg">you actually want to be</span></p>'},
  
 {g:'gA',id:'A5',rev:4,changed:'You approved this and asked only for a slower reveal. Done — but the reveal speed is GLOBAL, so this is no longer byte-identical to what you approved. Re-judging it is the honest call.',t:'A1 on the Team headline',
  why:'Same wipe again, line-team-lg.svg in pink. Third headline, third stroke, one mechanism.',
  html:'<p class="head blanco">The crew behind<br><span class="u wipe" data-k="line-team-lg" style="--strokec:var(--pink)">every single day.</span></p>'},
 {g:'gA',id:'A6',rev:4,changed:'Your rule applied: when the headline wraps, the stroke now fills only the BOTTOM line, measured from the last text rect. Resize the card or flip to Mobile 390 to force a re-measure.',t:'A1 on a long headline',
  why:'NOW FORCED TO WRAP (max-width:15ch) so the rule is actually visible — you denied this and you were right, it was not wrapping at desktop width so there was nothing to judge. When the span wraps, the stroke fills only the BOTTOM line, measured from the last text rect rather than the whole block. Resize the card or flip to Mobile 390 to force a different wrap and watch it re-measure.',
  html:'<p class="head blanco" style="max-width:15ch;margin-inline:auto">Great food, great people, <span class="u wipe" data-k="line-community-lg" style="--strokec:var(--orange)">epic communities everywhere</span></p>'},

{g:'gA',id:'S-A1',rev:1,salient:true,t:'SALIENT — basic-underline, exact',
  changed:'',
  why:'The reference, transcribed rather than approximated: your centreline stroke in Salient\'s own box (height 30%, sitting 20% below the words), 1.8s, round caps — now with EASE-OUT as you asked, rather than Salient\'s ease-in-out. S-A3 below is the same card with the reference easing, so you can see what we gave up. Note the keyframe holds opacity at 0 until 1% — at full dash offset a round cap paints a DOT, and that step hides it. Compare against A2 above, which is the same stroke on our old 0.72s ease-out.',
  html:'<p class="head blanco">Come work somewhere<br><span class="u sal draw" data-k="line-careers-lg">you actually want to be</span></p>'},
 {g:'gA',id:'S-A3',rev:1,salient:true,t:'SALIENT — same, with the reference easing',
  changed:'',
  why:'S-A1 with Salient\'s own cubic-bezier(.65,0,.35,1) instead of the ease-out you asked for. Side by side you can see what the ease-in gives up: it starts slower, so the stroke reads as being placed rather than flicked. If S-A1 now feels too eager, this is the alternative.',
  html:'<p class="head blanco">Come work somewhere<br><span class="u sal refease draw" data-k="line-careers-lg">you actually want to be</span></p>'},
 {g:'gA',id:'S-A2',rev:1,salient:true,t:'SALIENT — squiggle-underline-2 box, their path',
  changed:'',
  why:'The second variant running on the same Baked Bear page, using THEIR actual path data and box (height 50%, 45% below). It is a two-pass stroke — right, back, right again — so it reads as a scribble rather than a rule. This is what "multiple slight variations of this one" looks like in practice: same mechanism, different path and box.',
  html:'<p class="head blanco">Fresh baked<br><span class="u sal sq2 draw" data-k="_bb_squiggle">cookies every day.</span></p>'},

 {g:'gB',id:'S-B1',rev:1,salient:true,t:'SALIENT — fires only when FULLY on screen',
  changed:'',
  why:'STROKE THICKENED to .17em, per your note. THE ONE THAT EXPLAINS "not anytime before". Salient waits for bottom-in-view — the whole element on screen — where brgw.js fires at 16% visible. This card is observed at threshold 1.0; B1 above uses our current 0.45. Scroll them both past slowly and the difference is the whole complaint. NOTE: no full-page view for this card, deliberately — lab-full.html fires on a timer and has no scroll observation, so a full view here would play identically to B1 and quietly misrepresent the one thing this card exists to show.',
  thresh:1, nofull:true,
  html:'<p class="head blanco" data-split>Come work somewhere you actually want to be</p><span class="u sal blk draw" data-k="line-careers-lg"></span>',
  split:true,delay:'whole'},

 {g:'gB',id:'B1',rev:4,changed:'Placement is measured now, not guessed — the bar takes the width of the last line rather than a hardcoded 520px. Plus a timing dial, so you can hand me a number.',t:'After the whole headline — with a timing dial',
  why:'You said this lines up oddly and you wanted to test it. The slider below moves the stroke relative to the moment the last line lands: negative starts it while the headline is still arriving, positive holds it back. 0 = the instant the last line finishes. Watch the number, then tell me the one you want.',
  html:'<p class="head blanco" data-split>Come work somewhere you actually want to be</p><span class="u wipe blk" data-k="line-careers-lg"></span>',
  split:true,delay:'whole',dial:true},
 
 {g:'gC',id:'C1',rev:4,changed:'Back to simultaneous, as you asked: the box and its words animate together, after the text before them. The clipping mask is gone.',t:'Box first, then words',
  why:'BACK TO SIMULTANEOUS, as you asked — the box and the words it highlights now animate at the same time, after the text before them. The clipping mask is gone, which also fixes C5.',
  html:'<p class="head blanco">Born in San Diego.<br>Built <span class="mk tilt"><span class="tw"><span class="t">for community.</span></span></span></p>'},
   {g:'gC',id:'S-C1',rev:1,salient:true,t:'SALIENT — highlight, background-size wipe',
  changed:'',
  why:'The /menu/ hero treatment, transcribed: a linear-gradient on the words with background-size going 0 to 100% at 80% height, 0.9s cubic-bezier(.15,.75,.4,1), anchored at left 90%. The words stay visible throughout and the block sweeps in behind them. Better than the scaled box in C1 for one concrete reason — a background survives a wrapped line, a single stretched element does not. Deliberately faster than the 1.8s stroke.',
  html:'<p class="head blanco">Born in San Diego.<br>Built <span class="mk sal tilt"><span class="tw"><span class="t">for community.</span></span></span></p>'},
 {g:'gC',id:'S-C2',rev:1,salient:true,t:'SALIENT — highlight on the full line',
  changed:'',
  why:'Same wipe where the mark IS the whole line, which is the case that broke C5. Yellow, as on What we\'re about.',
  html:'<p class="head blanco"><span class="mk sal tilt" style="--mkc:var(--yellow);color:#231F20"><span class="tw"><span class="t">What we\u2019re about</span></span></span></p>'},

 {g:'gC',id:'C5',rev:4,changed:'Actually fixed, and the cause is named on the card: my clipping mask collapsed the box height whenever the mark was the whole line, so you saw a sliver instead of a bar.',t:'Yellow banner — What we’re about',
  why:'FIXED, and here is what was wrong: the words sat in an overflow:hidden mask with negative margins, and when the mark is the ENTIRE line — as it is here, unlike C1 — those margins collapsed the box height, so the yellow bar drew as a sliver behind the middle of the text. That is why you kept seeing part of it. Mask removed; identical to C1 now.',
  html:'<p class="head blanco"><span class="mk tilt" style="--mkc:var(--yellow)"><span class="tw"><span class="t">What we’re about</span></span></span></p>'},

 {g:'gD',id:'D1',rev:1,changed:'',t:'Draw in, un-draw out',
  why:'Leaving reverses the stroke back out, as the Osmo pen does.',
  html:'<div class="navbar"><a href="#">Our Story</a><a href="#">Team</a><a href="#" class="act">Careers</a><a href="#">Community</a></div>'},
 ];
